from: ${PROFZONE_DOCKER_REGISTRY}/profzone/golang:runtime
image: ${PROFZONE_DOCKER_REGISTRY}/${PROJECT_GROUP}/${PROJECT_NAME}:${PROJECT_VERSION}
workdir: /go/bin
env:
  GOENV: DEV
  S_CLIENTAUTH_HOST: service-in2-auth.in2store.rancher.internal
  S_CLIENTAUTH_PORT: "80"
  S_CLIENTBOOK_HOST: service-in2-book.in2store.rancher.internal
  S_CLIENTBOOK_PORT: "80"
  S_CLIENTUSER_HOST: service-in2-user.in2store.rancher.internal
  S_CLIENTUSER_PORT: "80"
  S_LOG_FORMAT: json
  S_SERVER_PORT: "80"
  S_SERVER_WITHCORS: "false"
add:
  ./config: ./config
  ./profzone.yml: ./
  ./service-in2-gateway: ./
  ./swagger.json: ./
expose:
- "80"
cmd:
- ./service-in2-gateway
- -c=false
